services:
  {{- if .nginx}}
  nginx:
    image: {{.nginx.image}}
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - 80:80
  {{- if .websocket}}
    depends_on:
      - websocket
  {{- end}}
  {{- end}}

  {{- if .websocket}}
  websocket:
    container_name: websocket
    environment:
      - WEBSOCKET_PORT={{- template "websocketport" .}}
      - RESPONSE={{- .websocket.response}}
    restart: always
    {{- if not .nginx}}
    ports:
      - 80:{{- template "websocketport" .}}
    {{- end}}
    build:
      context: ./websocket
      dockerfile: Dockerfile
  {{- end}}
