# Copyright(C) 2024, Stamus Networks
# Written by RaphaÃ«l Brogat <rbrogat@stamus-networks.com> and Valentin Vivier <vvivier@stamus-networks.com>
#
# This file comes with ABSOLUTELY NO WARRANTY!
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '3.4'

networks:
  network:

volumes:
  suricata-rules: #for suricata rules transfer between scirius and suricata and for persistency
  suricata-run: #path where the suricata socket resides
  suricata-logs:
  suricata-logrotate:
  {{- if .elk.elastic }}
  elastic-data:  #for ES data persistency
  {{- end }}
  {{- if .scirius }}
  scirius-data: #for scirius data persistency
  scirius-static: #statics files to be served by nginx
  {{- end }}
  {{- if .elk.logstash }}
  logstash-sincedb: #where logstash stores it's state so it doesn't re-ingest
  {{- end }}
  {{- if .arkimeviewer }}
  arkime-logs:
  arkime-pcap:
  arkime-config:
  {{- end }}
  db-data:


services:
  {{- if .elk.elastic }}
  elasticsearch:
    container_name: elasticsearch
    image: elastic/elasticsearch:{{.elk.version}}
    restart: {{ .globals.restartmode | default "unless-stopped" }}
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.ml.enabled={{.elk.elastic.ml | default "false"}}
      - ingest.geoip.downloader.enabled=false
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    mem_limit: {{ .elk.elastic.memory | default "3G" }}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      network:
  {{- end }}

  {{- if .elk.kibana }}
  kibana:
    container_name: kibana
    image:  elastic/kibana:{{.elk.version}}
    restart: {{ .globals.restartmode | default "unless-stopped" }}
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:5601 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      network:
  {{- end }}

  {{- if .elk.logstash }}
  # if logstash is enabled
  logstash:
    container_name: logstash
    image:  elastic/logstash:{{.elk.version}}
    restart: {{ .globals.restartmode | default "unless-stopped" }}
    depends_on:
      scirius:
        condition: service_healthy #because we need to wait for scirius to populate ILM policy
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9600 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    mem_limit: {{.elk.logstash.memory | default "3G"}}
    volumes:
      - logstash-sincedb:/since.db
      - {{.globals.volumepath}}/suricata/logs:/var/log/suricata:ro
      - {{.globals.volumepath}}/logstash/conf.d/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - {{.globals.volumepath}}/logstash/templates/elasticsearch7-template.json:/usr/share/logstash/config/elasticsearch7-template.json
    networks:
      network:
  {{- end }}

  suricata:
    container_name: suricata
    image: jasonish/suricata:master-amd64
    entrypoint: /etc/suricata/new_entrypoint.sh
    restart: {{ .globals.restartmode | default "unless-stopped" }}
    environment:
      - SURICATA_OPTIONS= -i {{.suricata.interfaces | default "dummy0"}} -vvv --set sensor-name=suricata
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    network_mode: host
    volumes:
      {{- if and .suricata.logs .suricata.logs.file }}
       - {{ .globals.volumepath }}/{{ .suricata.logs.file.hostPath | default "suricata/logs" }}:{{ .suricata.logs.file.internalPath | default "/var/log/suricata" }}
      {{- end }}
       - suricata-rules:/etc/suricata/rules
       - suricata-run:/var/run/suricata/
       - {{.globals.volumepath}}/suricata/etc:/etc/suricata
       - suricata-logrotate:/etc/logrotate.d/

  {{- if .scirius }}
  scirius:
    container_name: scirius
    image: {{.registry | default "ghcr.io/stamusnetworks"}}/scirius:{{.SciriusVersion | default "master"}}
    restart: {{ .globals.restartmode | default "unless-stopped" | default "unless-stopped"}}
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      {{- if .elk.kibana }}
      kibana:
        condition: service_healthy
      {{- end }}
    healthcheck:
      interval: 10s
      timeout: 1s
      retries: 5
      start_period: 5m
    environment:
      - DATABASE_TYPE=pg
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=selks
      - DATABASE_USERNAME=selks
      - DATABASE_PASSWORD=selks
      - SECRET_KEY={{.scirius.token | default ""}}
      - DEBUG={{.scirius.debug | default "false"}}
      - ALLOWED_HOSTS=* #allow connexions from anywhere
      - SCIRIUS_IN_SELKS=True
      - USE_ELASTICSEARCH=True
      - ELASTICSEARCH_ADDRESS=elasticsearch:9200
      - SURICATA_UNIX_SOCKET=/var/run/suricata/suricata-command.socket
      - USE_SURICATA_STATS=True
      - USE_KIBANA={{if .elk.kibana }}True{{ else }}False{{ end }}
      {{- if .elk.kibana }}
      - KIBANA_URL=http://kibana:5601
      - KIBANA_PROXY=True
      - KIBANA7_DASHBOARDS_PATH=/opt/selks/kibana7-dashboards
      {{- end }}
      - USE_EVEBOX={{if .evebox }}True{{ else }}False{{ end }}
      {{- if .evebox }}
      - EVEBOX_ADDRESS=evebox:5636
      {{- end }}
      - USE_MOLOCH={{if .arkimeviewer }}True{{ else }}False{{ end }}
      {{- if .arkimeviewer }}
      - MOLOCH_URL=http://arkime:8005
      {{- end }}
    volumes:
      - scirius-static:/static/
      - scirius-data:/data/
      - {{.globals.volumepath}}/scirius/logs/:/logs/
      - suricata-rules:/rules
      - suricata-run:/var/run/suricata
      - {{.globals.volumepath}}/suricata/logs:/var/log/suricata:ro

    networks:
      network:
  {{- end }}

  {{- if .evebox }}
  evebox:
    container_name: evebox
    image: jasonish/evebox:master
    command: ["-e", "http://elasticsearch:9200"]
    restart: {{ .globals.restartmode | default "unless-stopped" }}
    environment:
      - EVEBOX_HTTP_TLS_ENABLED=false
      - EVEBOX_AUTHENTICATION_REQUIRED=false
    networks:
      network:
  {{- end }}

  nginx:
    container_name: nginx
    image: nginx
    command: ['{{.NginxExec | default "nginx"}}', '-g', 'daemon off;']
    restart: {{ .globals.restartmode | default "unless-stopped" }}
    depends_on:
      scirius: #we need to wait for scirius to populate the static files
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'service', 'nginx', 'status']
      interval: 10s
      timeout: 2s
      retries: 5
    volumes:
      - scirius-static:/static/:ro
      - {{.globals.volumepath}}/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - {{.globals.volumepath}}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - {{.globals.volumepath}}/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - 443:443
    networks:
      network:

  cron:
    # This containers handles crontabs for the other containers, following the 1 task per container principle.
    # It is based on  'docker:latest' image, wich is an alpine image with docker binary
    container_name: cron
    image: docker:latest
    command: [sh, -c, "echo '*	*	 *	*	 *	run-parts /etc/periodic/1min' >> /etc/crontabs/root && crond -f -l 8"]
    restart: {{ .globals.restartmode | default "unless-stopped" }}
    healthcheck:
      test: ['CMD', 'ps', '|', 'grep', 'crond']
      interval: 1m
      timeout: 1m
      retries: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # This bind-mout allows using the hosts docker daemon instead of created one inside the container

      # Those volumes will contain the cron jobs
      - {{.globals.volumepath}}/cron-jobs/1min:/etc/periodic/1min/:ro
      - {{.globals.volumepath}}/cron-jobs/15min:/etc/periodic/15min/:ro
      - {{.globals.volumepath}}/cron-jobs/daily:/etc/periodic/daily/:ro
      - {{.globals.volumepath}}/cron-jobs/hourly:/etc/periodic/hourly/:ro
      - {{.globals.volumepath}}/cron-jobs/monthly:/etc/periodic/monthly/:ro
      - {{.globals.volumepath}}/cron-jobs/weekly:/etc/periodic/weekly/:ro


  {{- if .arkimeviewer }}
  arkime:
    container_name: arkime
    image: {{.registry}}/arkimeviewer:{{(.arkimeviewer).version | default "master"}} ## Repo will need to be changed to stamusnetwork once image built
    restart: {{ .globals.restartmode | default "unless-stopped" }}
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://scirius:8000/moloch']
      interval: 15s
      timeout: 5s
      retries: 3
    volumes:
      - {{.globals.volumepath}}/suricata/logs:/suricata-logs:ro
      - arkime-config:/data/config
      - arkime-pcap:/data/pcap
      - arkime-logs:/data/logs
    networks:
      network:
  {{- end }}

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: selks
      POSTGRES_PASSWORD: selks
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U selks']
      interval: 5s
      timeout: 1s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      network: